[2024-11-22T14:46:18.073+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T14:46:18.110+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T14:46:18.110+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T14:46:18.183+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T14:46:18.204+0000] {standard_task_runner.py:60} INFO - Started process 583 to run task
[2024-11-22T14:46:18.214+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpj6xv71sx']
[2024-11-22T14:46:18.219+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask save_to_postgres
[2024-11-22T14:46:18.335+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 370c84c603a0
[2024-11-22T14:46:18.559+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T14:46:18.569+0000] {python.py:201} INFO - Done. Returned value was: {{ task_instance.xcom_pull(task_ids='insert_data_to_postgres', dag_id='adhoc_airflow', key='return_value') }}
[2024-11-22T14:46:18.594+0000] {xcom.py:664} ERROR - Object of type PlainXComArg is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-11-22T14:46:18.599+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class '***.models.xcom_arg.PlainXComArg'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PlainXComArg is not JSON serializable
[2024-11-22T14:46:18.631+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T144618, end_date=20241122T144618
[2024-11-22T14:46:18.666+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task save_to_postgres (Object of type PlainXComArg is not JSON serializable; 583)
[2024-11-22T14:46:18.703+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T14:46:18.747+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:02:40.630+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:02:40.654+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:02:40.655+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:02:40.699+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:02:40.709+0000] {standard_task_runner.py:60} INFO - Started process 392 to run task
[2024-11-22T15:02:40.720+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp118_1vho']
[2024-11-22T15:02:40.726+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask save_to_postgres
[2024-11-22T15:02:40.850+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 892507b96f2b
[2024-11-22T15:02:41.046+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:02:41.066+0000] {python.py:201} INFO - Done. Returned value was: {{ task_instance.xcom_pull(task_ids='insert_data_to_postgres', dag_id='adhoc_airflow', key='return_value') }}
[2024-11-22T15:02:41.087+0000] {xcom.py:664} ERROR - Object of type PlainXComArg is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-11-22T15:02:41.097+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class '***.models.xcom_arg.PlainXComArg'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PlainXComArg is not JSON serializable
[2024-11-22T15:02:41.185+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T150240, end_date=20241122T150241
[2024-11-22T15:02:41.224+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task save_to_postgres (Object of type PlainXComArg is not JSON serializable; 392)
[2024-11-22T15:02:41.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T15:02:41.335+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:16:48.440+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:16:48.462+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:16:48.462+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:16:48.483+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:16:48.492+0000] {standard_task_runner.py:60} INFO - Started process 1120 to run task
[2024-11-22T15:16:48.497+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp7vii2bws']
[2024-11-22T15:16:48.502+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask save_to_postgres
[2024-11-22T15:16:48.590+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 892507b96f2b
[2024-11-22T15:16:48.701+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:16:48.704+0000] {python.py:201} INFO - Done. Returned value was: {{ task_instance.xcom_pull(task_ids='insert_data_to_postgres', dag_id='adhoc_airflow', key='return_value') }}
[2024-11-22T15:16:48.716+0000] {xcom.py:664} ERROR - Object of type PlainXComArg is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-11-22T15:16:48.718+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class '***.models.xcom_arg.PlainXComArg'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PlainXComArg is not JSON serializable
[2024-11-22T15:16:48.736+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T151648, end_date=20241122T151648
[2024-11-22T15:16:48.751+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task save_to_postgres (Object of type PlainXComArg is not JSON serializable; 1120)
[2024-11-22T15:16:48.762+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T15:16:48.786+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:26:30.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:26:30.997+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:26:30.999+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:26:31.022+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:26:31.030+0000] {standard_task_runner.py:60} INFO - Started process 1790 to run task
[2024-11-22T15:26:31.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp1m28ixn2']
[2024-11-22T15:26:31.043+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask save_to_postgres
[2024-11-22T15:26:31.128+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 892507b96f2b
[2024-11-22T15:26:31.238+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:26:31.254+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-22T15:26:31.274+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-11-22T15:26:31.290+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T152630, end_date=20241122T152631
[2024-11-22T15:26:31.343+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-22T15:26:31.370+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:40:18.719+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:40:18.732+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:40:18.733+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:40:18.751+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:40:18.757+0000] {standard_task_runner.py:60} INFO - Started process 396 to run task
[2024-11-22T15:40:18.766+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp9lvagewq']
[2024-11-22T15:40:18.770+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask save_to_postgres
[2024-11-22T15:40:19.022+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 7003e752bc1d
[2024-11-22T15:40:19.259+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:40:19.278+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-22T15:40:19.286+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/task.py", line 66, in insert_data_to_postgres
    cursor.execute(
psycopg2.errors.SyntaxError: syntax error at or near "date"
LINE 4:                     ON CONFLICT date DO UPDATE
                                        ^

[2024-11-22T15:40:19.308+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T154018, end_date=20241122T154019
[2024-11-22T15:40:19.333+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task save_to_postgres (syntax error at or near "date"
LINE 4:                     ON CONFLICT date DO UPDATE
                                        ^
; 396)
[2024-11-22T15:40:19.370+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T15:40:19.407+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:41:32.510+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:41:32.524+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:41:32.525+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:41:32.543+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:41:32.549+0000] {standard_task_runner.py:60} INFO - Started process 490 to run task
[2024-11-22T15:41:32.554+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpkfrpo2_7']
[2024-11-22T15:41:32.558+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask save_to_postgres
[2024-11-22T15:41:32.673+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 7003e752bc1d
[2024-11-22T15:41:32.804+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:41:32.823+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-22T15:41:32.839+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/task.py", line 66, in insert_data_to_postgres
    cursor.execute(
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-11-22T15:41:32.866+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T154132, end_date=20241122T154132
[2024-11-22T15:41:32.888+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task save_to_postgres (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 490)
[2024-11-22T15:41:32.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T15:41:32.952+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:44:04.914+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:44:04.928+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:44:04.928+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:44:04.946+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:44:04.951+0000] {standard_task_runner.py:60} INFO - Started process 663 to run task
[2024-11-22T15:44:04.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpykpg7xuu']
[2024-11-22T15:44:04.960+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask save_to_postgres
[2024-11-22T15:44:05.036+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host 7003e752bc1d
[2024-11-22T15:44:05.138+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:44:05.151+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-22T15:44:05.161+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/task.py", line 66, in insert_data_to_postgres
    cursor.execute(
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-11-22T15:44:05.178+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T154404, end_date=20241122T154405
[2024-11-22T15:44:05.193+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task save_to_postgres (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 663)
[2024-11-22T15:44:05.218+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T15:44:05.246+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:50:46.894+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:50:46.940+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:50:46.943+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-11-22T15:50:47.040+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:50:47.079+0000] {standard_task_runner.py:60} INFO - Started process 387 to run task
[2024-11-22T15:50:47.088+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'work_task', 'save_to_postgres', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp5qcryi0j']
[2024-11-22T15:50:47.094+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask save_to_postgres
[2024-11-22T15:50:48.168+0000] {task_command.py:423} INFO - Running <TaskInstance: work_task.save_to_postgres scheduled__2024-11-21T00:00:00+00:00 [running]> on host e3d4853ded5c
[2024-11-22T15:50:48.928+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='work_task' AIRFLOW_CTX_TASK_ID='save_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:50:49.028+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-22T15:50:49.081+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-11-22T15:50:49.111+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=work_task, task_id=save_to_postgres, execution_date=20241121T000000, start_date=20241122T155046, end_date=20241122T155049
[2024-11-22T15:50:49.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-22T15:50:49.257+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
